title:            Tinker's thoughts~
description:      ...
url:              # Site url, without a slash at the end.
signoff:          Dulitha
disqus_shortname: duli-chan
facebook_appid:   164540446948
google_analytics: UA-47839614-1

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /blog
  - name:         GitHub
    url:          http://github.com/dulichan
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
gems: ["octopress-image-tag", "octopress-codeblock", "octopress-quote-tag", "octopress-gist", "octopress-codefence", "octopress-solarized"]
redcarpet:
  extensions:
    - smart
